### ISSUE TITLE
Some questions about logs(View the AntiDDos exception event)

### ISSUE THREAD

**Issue by zy36128169** [Huawei/OpenStackClient_AntiDDOS#1]
输入
openstack antiddos logs 10.154.55.93(any valid floatingIP) --insecure
没有获得任何信息

**Comment by IamFive** [comment]
我测试的时候，服务器也是返回空数据，不知道要如何产生 这些数据。

是不是要模拟下 antiddos 攻击还是撒。或者马伍那边帮忙在后台生成一些数据。

**Comment by IamFive** [comment]
环境未有数据，非功能问题。
