### ISSUE TITLE
Python-openstackclient 2.4.0环境，告警命令bug 

### ISSUE THREAD

**Issue by zy36128169** [Huawei/OpenStackClient_AntiDDOS#10]
信息反馈如下：
root@11111111:/home/ubuntu/OpenStackClient_AntiDDOS-master# openstack antiddos alert config show --os-antiddos-api-version=2 --insecure

openstack: 'antiddos alert config show' is not an openstack command. See 'openstack --help'.

**Comment by IamFive** [comment]
这个没法解决，只有 3.9.0 以后的版本才可以。
