### ISSUE TITLE
Python-openstackclient 2.4.0环境, 测试问题

### ISSUE THREAD

**Issue by zy36128169** [Huawei/OpenStackClient_AntiDDOS#12]
(一)
执行openstack antiddos open 10.154.55.93 --maximum-service-traffic=30 --debug --insecure

log:
REQ: curl -g -i --insecure -X POST https://antiddos.eu-de.otc.t-systems.com/v1/2517cd17c4ef4d6c8707cbae21d59b6d/antiddos/1a194596-ceff-407e-9721-f33e2da8a968 -H "User-Agent: python-openstackclient keystoneauth1/2.19.0 python-requests/2.12.0 CPython/2.7.12" -H "Content-Type: application/json" -H "Accept: application/json" -H "X-Auth-Token: {SHA1}1c06ada3a41d52560e39aafc96a5fee5436e85cb" -d '{"cleaning_access_pos_id": 8, "enable_L7": true, "traffic_pos_id": 2, "app_type_id": 1}'
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py:843: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
https://antiddos.eu-de.otc.t-systems.com:443 "POST /v1/2517cd17c4ef4d6c8707cbae21d59b6d/antiddos/1a194596-ceff-407e-9721-f33e2da8a968 HTTP/1.1" 400 102
RESP: [400] Server: Web Server Date: Wed, 19 Apr 2017 11:51:27 GMT Content-Type: application/json; charset=UTF-8 Content-Length: 102 Connection: keep-alive X-Frame-Options: SAMEORIGIN Cache-Control: no-cache X-Content-Type-Options: nosniff X-Download-Options: noopen Pragma: no-cache Expires: Thu, 01 Jan 1970 00:00:00 GMT X-XSS-Protection: 1; mode=block 
RESP BODY: {"error_code":"10001003", "error_description":"An invalid HTTP request triggering parameter is used."}

Request returned failure status: 400
[10001003] An invalid HTTP request triggering parameter is used. (HTTP 400)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cliff/app.py", line 400, in run_subcommand
    result = cmd.run(parsed_args)
  File "/usr/local/lib/python2.7/dist-packages/osc_lib/command/command.py", line 41, in run
    return super(Command, self).run(parsed_args)
  File "/usr/local/lib/python2.7/dist-packages/cliff/command.py", line 90, in run
    return self.take_action(parsed_args) or 0
  File "/usr/local/lib/python2.7/dist-packages/antiddosclient/osc/v1/antiddos.py", line 70, in take_action
    1)
  File "/usr/local/lib/python2.7/dist-packages/antiddosclient/v1/antiddos_mgr.py", line 79, in open_antiddos
    raw=True)
  File "/usr/local/lib/python2.7/dist-packages/antiddosclient/common/manager.py", line 101, in _create
    resp, body = self.http_client.post(url, json=data, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/keystoneauth1/adapter.py", line 229, in post
    return self.request(url, 'POST', **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/antiddosclient/common/httpclient.py", line 56, in request
    raise exceptions.from_http_error(http)
BadRequest: [10001003] An invalid HTTP request triggering parameter is used. (HTTP 400)

少了http-request-rate 参数，还会继续向服务器发送请求，此时应该这样提示
openstack antiddos open: error: argument --maximum-service-traffic is required
而不是直接向服务器发送请求

(二)
执行openstack antiddos open 10.154.55.93 --disable-CC --maximum-service-traffic=30 --http-request-rate=350 --insecure

可以正常执行，数据没有问题，但是用户体验不好；
此时应该提示当disable-CC的时候，不需要http-request-rate参数

(三)
执行openstack antiddos set 10.154.55.93 --disable-CC --maximum-service-traffic=30 --http-request-rate=350 --insecure

可以正常执行，数据没有问题，但是用户体验不好；
此时应该提示当disable-CC的时候，不需要http-request-rate参数

(四)

第一次执行openstack antiddos set 10.154.55.93 --disable-CC --maximum-service-traffic=50 --insecure

log:
REQ: curl -g -i --insecure -X PUT https://antiddos.eu-de.otc.t-systems.com/v1/2517cd17c4ef4d6c8707cbae21d59b6d/antiddos/1a194596-ceff-407e-9721-f33e2da8a968 -H "User-Agent: python-openstackclient keystoneauth1/2.19.0 python-requests/2.12.0 CPython/2.7.12" -H "Content-Type: application/json" -H "Accept: application/json" -H "X-Auth-Token: {SHA1}9520fc2a1bf3ba2cc5a4665833d06fdcf7b47db4" -d '{"cleaning_access_pos_id": 8, "enable_L7": false, "http_request_pos_id": 15, "traffic_pos_id": 3, "app_type_id": 1}'
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py:843: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
https://antiddos.eu-de.otc.t-systems.com:443 "PUT /v1/2517cd17c4ef4d6c8707cbae21d59b6d/antiddos/1a194596-ceff-407e-9721-f33e2da8a968 HTTP/1.1" 200 None
RESP: [200] Server: Web Server Date: Wed, 19 Apr 2017 12:01:24 GMT Content-Type: application/json Transfer-Encoding: chunked Connection: keep-alive Cache-Control: private, no-store, no-cache Expires: Thu, 01 Jan 1970 08:00:00 CST, Thu, 01 Jan 1970 00:00:00 GMT Pragma: no-cache X-Frame-Options: SAMEORIGIN, DENY X-Content-Type-Options: nosniff, nosniff X-Download-Options: noopen, noopen X-XSS-Protection: 1; mode=block, 1; mode=block; Strict-Transport-Security: max-age=31536000; includeSubdomains; 
RESP BODY: {"error_code":"10000000","error_description":"Task has been received and is being processed.","task_id":"6e8b8fd5-7d21-4e54-b90f-779410fe7e54"}

--返回值200，RESP BODY: {"error_code":"10000000","error_description":"Task has been received and is being processed.","task_id":"6e8b8fd5-7d21-4e54-b90f-779410fe7e54"}

重复执行openstack antiddos set 10.154.55.93 --disable-CC --maximum-service-traffic=50 --insecure（更新的参数值和之前的一样）

log:
REQ: curl -g -i --insecure -X PUT https://antiddos.eu-de.otc.t-systems.com/v1/2517cd17c4ef4d6c8707cbae21d59b6d/antiddos/1a194596-ceff-407e-9721-f33e2da8a968 -H "User-Agent: python-openstackclient keystoneauth1/2.19.0 python-requests/2.12.0 CPython/2.7.12" -H "Content-Type: application/json" -H "Accept: application/json" -H "X-Auth-Token: {SHA1}17ef863b71c73b986c61eb76593ccc3d9f5a1b72" -d '{"cleaning_access_pos_id": 8, "enable_L7": false, "http_request_pos_id": 15, "traffic_pos_id": 3, "app_type_id": 1}'
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py:843: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
https://antiddos.eu-de.otc.t-systems.com:443 "PUT /v1/2517cd17c4ef4d6c8707cbae21d59b6d/antiddos/1a194596-ceff-407e-9721-f33e2da8a968 HTTP/1.1" 200 0
RESP: [200] Server: Web Server Date: Wed, 19 Apr 2017 12:02:57 GMT Content-Type: application/json; charset=UTF-8 Content-Length: 0 Connection: keep-alive Cache-Control: private, no-cache Expires: Thu, 01 Jan 1970 00:00:00 GMT, Thu, 01 Jan 1970 00:00:00 GMT X-Frame-Options: SAMEORIGIN, DENY X-Content-Type-Options: nosniff, nosniff X-Download-Options: noopen, noopen Pragma: no-cache X-XSS-Protection: 1; mode=block, 1; mode=block; Strict-Transport-Security: max-age=31536000; includeSubdomains;
string indices must be integers, not str
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cliff/app.py", line 400, in run_subcommand
    result = cmd.run(parsed_args)
  File "/usr/local/lib/python2.7/dist-packages/osc_lib/command/command.py", line 41, in run
    return super(Command, self).run(parsed_args)
  File "/usr/local/lib/python2.7/dist-packages/cliff/command.py", line 90, in run
    return self.take_action(parsed_args) or 0
  File "/usr/local/lib/python2.7/dist-packages/antiddosclient/osc/v1/antiddos.py", line 142, in take_action
    return 'Request Received, task id: ' + task['task_id']
TypeError: string indices must be integers, not str

--返回200

重复执行openstack antiddos set 10.154.55.93 --disable-CC --maximum-service-traffic=50 --insecure（更新的参数值和之前的一样）会继续向服务器发送请求
重复执行openstack antiddos set 10.154.55.93 --disable-CC --maximum-service-traffic=50 --insecure（更新的参数值和之前的一样）,提示如下信息：string indices must be integers, not str，这个提示信息不合适吧

**Comment by zy36128169** [comment]
执行openstack antiddos show 10.154.55.93 --insecure
显示如下：
| Field                   | Value     |
+-------------------------+-----------+
| CC Defense              | Disabled  |
| maximum service traffic | 100Mbit/s |
| http request rate       | 20000/s   |

此时10.154.55.93的配置是 --disable-CC，maximum-service-traffic=100
disable-CC的情况就不需要显示http request rate的信息了

**Comment by IamFive** [comment]
2，3 是重复了吗。
4是服务器端问题。客户端不会处理。

**Comment by IamFive** [comment]
1,2,3这种问题 客户端本来是都不会管的。验证的逻辑服务端就应该要有了。
