### ISSUE TITLE
some questions about weekly

### ISSUE THREAD

**Issue by zy36128169** [Huawei/OpenStackClient_AntiDDOS#7]
DDOS intercept times     Weekly data      top10        
这三个值加个下划线区别开来
                                      
Field                                                                 
---------------------------------------------------------------------------------------------
DDOS intercept times     
---------------------------------------------------------------------------------------------
Weekly data                     
---------------------------------------------------------------------------------------------
top10

**Comment by IamFive** [comment]
输出结构是 python-openstackclient 决定的。没提供添加分割线的选项。
插件这边是负责提供要输出的数据，输出结构不在插件这边控制。
