### ISSUE TITLE
Python-openstackclient 2.4.0环境，openstack antiddos open参数是UUID的时候失败

### ISSUE THREAD

**Issue by zy36128169** [Huawei/OpenStackClient_AntiDDOS#9]
root@11111111:/home/ubuntu/OpenStackClient_AntiDDOS-master# openstack antiddos open 1a194596-ceff-407e-9721-f33e2da8a968 --maximum-service-traffic=30 --http-request-rate=1000 --insecure

log:

REQ: curl -g -i --insecure -X GET https://antiddos.eu-de.otc.t-systems.com/v1/2517cd17c4ef4d6c8707cbae21d59b6d/antiddos/1a194596-ceff-407e-9721-f33e2da8a968 -H "User-Agent: python-openstackclient keystoneauth1/2.19.0 python-requests/2.12.0 CPython/2.7.12" -H "Accept: application/json" -H "X-Auth-Token: {SHA1}a5e9c08d016cc09692de0c3006c3ae4628faee6c"
Starting new HTTPS connection (1): antiddos.eu-de.otc.t-systems.com
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py:843: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
https://antiddos.eu-de.otc.t-systems.com:443 "GET /v1/2517cd17c4ef4d6c8707cbae21d59b6d/antiddos/1a194596-ceff-407e-9721-f33e2da8a968 HTTP/1.1" 200 0
RESP: [200] Server: Web Server Date: Tue, 18 Apr 2017 09:16:40 GMT Content-Type: application/json; charset=UTF-8 Content-Length: 0 Connection: keep-alive Cache-Control: private, no-cache Expires: Thu, 01 Jan 1970 08:00:00 CST, Thu, 01 Jan 1970 00:00:00 GMT X-Frame-Options: SAMEORIGIN, DENY X-Content-Type-Options: nosniff, nosniff X-Download-Options: noopen, noopen Pragma: no-cache X-XSS-Protection: 1; mode=block, 1; mode=block; Strict-Transport-Security: max-age=31536000; includeSubdomains;
'StrWithMeta' object has no attribute 'floating_ip_id'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cliff/app.py", line 400, in run_subcommand
    result = cmd.run(parsed_args)
  File "/usr/local/lib/python2.7/dist-packages/osc_lib/command/command.py", line 41, in run
    return super(Command, self).run(parsed_args)
  File "/usr/local/lib/python2.7/dist-packages/cliff/command.py", line 90, in run
    return self.take_action(parsed_args) or 0
  File "/usr/local/lib/python2.7/dist-packages/antiddosclient/osc/v1/antiddos.py", line 64, in take_action
    task = client.antiddos.open_antiddos(floating_ip.floating_ip_id,
AttributeError: 'StrWithMeta' object has no attribute 'floating_ip_id'
clean_up OpenAntiDDos: 'StrWithMeta' object has no attribute 'floating_ip_id'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/openstackclient/shell.py", line 119, in run
    ret_val = super(OpenStackShell, self).run(argv)
  File "/usr/local/lib/python2.7/dist-packages/cliff/app.py", line 279, in run
    result = self.run_subcommand(remainder)
  File "/usr/local/lib/python2.7/dist-packages/openstackclient/shell.py", line 164, in run_subcommand
    ret_value = super(OpenStackShell, self).run_subcommand(argv)
  File "/usr/local/lib/python2.7/dist-packages/cliff/app.py", line 400, in run_subcommand
    result = cmd.run(parsed_args)
  File "/usr/local/lib/python2.7/dist-packages/osc_lib/command/command.py", line 41, in run
    return super(Command, self).run(parsed_args)
  File "/usr/local/lib/python2.7/dist-packages/cliff/command.py", line 90, in run
    return self.take_action(parsed_args) or 0
  File "/usr/local/lib/python2.7/dist-packages/antiddosclient/osc/v1/antiddos.py", line 64, in take_action
    task = client.antiddos.open_antiddos(floating_ip.floating_ip_id,
AttributeError: 'StrWithMeta' object has no attribute 'floating_ip_id'

**Comment by IamFive** [comment]
确认你们服务端是不是改接口了。。。

下面这个获取antiddos的接口没取到返回值

```
https://antiddos.eu-de.otc.t-systems.com:443 "GET /v1/2517cd17c4ef4d6c8707cbae21d59b6d/antiddos/1a194596-ceff-407e-9721-f33e2da8a968 HTTP/1.1" 200 0
RESP: [200] Server: Web Server Date: Tue, 18 Apr 2017 09:16:40 GMT Content-Type: application/json; charset=UTF-8 Content-Length: 0 Connection: keep-alive Cache-Control: private, no-cache Expires: Thu, 01 Jan 1970 08:00:00 CST, Thu, 01 Jan 1970 00:00:00 GMT X-Frame-Options: SAMEORIGIN, DENY X-Content-Type-Options: nosniff, nosniff X-Download-Options: noopen, noopen Pragma: no-cache X-XSS-Protection: 1; mode=block, 1; mode=block; Strict-Transport-Security: max-age=31536000; includeSubdomains;
```

**Comment by zy36128169** [comment]
参数是ip的时候日志信息这样
openstack antiddos open 10.154.55.93 --maximum-service-traffic=30 --http-request-rate=1000 --debug –insecure（命令能正常执行）

log信息：
https://antiddos.eu-de.otc.t-systems.com:443 "GET /v1/2517cd17c4ef4d6c8707cbae21d59b6d/antiddos?ip=10.154.55.93 HTTP/1.1" 200 None
RESP: [200] Server: Web Server Date: Tue, 18 Apr 2017 11:22:32 GMT Content-Type: application/json Transfer-Encoding: chunked Connection: keep-alive Cache-Control: private, no-store, no-cache Expires: Thu, 01 Jan 1970 00:00:00 GMT, Thu, 01 Jan 1970 00:00:00 GMT Pragma: no-cache X-Frame-Options: SAMEORIGIN, DENY X-Content-Type-Options: nosniff, nosniff X-Download-Options: noopen, noopen X-XSS-Protection: 1; mode=block, 1; mode=block; Strict-Transport-Security: max-age=31536000; includeSubdomains; 
RESP BODY: {"total":5,"ddosStatus":[{"floating_ip_id":"1a194596-ceff-407e-9721-f33e2da8a968","floating_ip_address":"10.154.55.93","network_type":"EIP","status":"notConfig"}]}

**Comment by IamFive** [comment]
ip 跟 id 是两个不同的接口查询的。

**Comment by IamFive** [comment]
需要确认的东西：

1. 4.4 查询Anti-DDoS服务 接口要展示什么数据（已配置|未配置）
2. 根据 floating ip id 如何找到对应的 antiddos 设置 （已配置|未配置），能不能在 4.7 查询EIP防护状态列表 接口中添加一个 id的查询条件

**Comment by zy36128169** [comment]
接口不能改哈
